export const button = "button"
export const loginButton = 'Log in'
export const vmware = 'VMware'
export const addProvider = 'Add provider'
export const selectProviderType = 'Select a provider type...'
export const remove = 'Remove'
export const sProvider = "Select a source provider..."
export const tProvider = "Select a target provider..."
export const source = 'Select source...'
export const destination = 'Select target...'
export const create = 'Create'
export const network = 'Network'
export const storage = 'Storage'
export const tr = 'tr'
export const mappings = 'Mappings'
export const createMapping = 'Create mapping'
export const migrationPLan = 'Migration Plans'
export const createPlan = 'Create plan'